title: SeanPerryman.com
email: se@nperryman.com
description: >- # this means to ignore newlines until "baseurl:"
  Just another place I can NOT keep up on my writing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seanperryman.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  sean-perryman

# Build settings
theme: minima
plugins:
  - jekyll-feed
